Repository nikhilbadyal/docker-py-revanced, pull requests merged in 2023-08, with the labels that each got.

#232 🐛 Fixed messenger url
  src/config.py
Labels: enhancement

#236 🐛 Handle updated patch name
  .github/workflows/build-artifact.yml
  apks/options.json
  apks/populate_client_id.sh
Labels: bug

#237 🐛 Updated messenger config
  src/config.py
Labels: bug

#238 ✨ Check new supported apps
  .github/workflows/build-apk.yml
  .github/workflows/build-artifact.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/status_check.yml
  scripts/__init__.py
  scripts/status_check.py
  src/patches.py
Labels: enhancement

#241 🐛 Create issue and not PR
  .github/workflows/newapp-check.yml
Labels: enhancement

#249 👷 Generate issue with image
  .github/workflows/newapp-check.yml
  scripts/status_check.py
Labels: enhancement

#239 230 custom patch resources
  .gitignore
  README.md
  main.py
  src/app.py
  src/config.py
  src/downloader/apkmirror.py
  src/downloader/download.py
  src/downloader/github.py
  src/downloader/utils.py
  src/parser.py
  src/patches.py
  src/utils.py
Labels: enhancement

#255 ✨ Added apkcombo scrapper
  scripts/status_check.py
  src/exceptions.py
Labels: enhancement

#260 ✨ Ability to upload extra files
  README.md
  main.py
  src/app.py
  src/config.py
  src/utils.py
Labels: feature-request👓, size/M

#264 🐛 Filter .apk for now
  src/utils.py
Labels: bug🐞, size/XS

#268 💚 Custom Resource Download
  .env.example
  main.py
  src/app.py
  src/downloader/download.py
  src/downloader/github.py
  src/exceptions.py
  src/parser.py
  src/utils.py
Labels: bug🐞, size/L

#272 ✨ Ability to provide patch resource locally
  .env.example
  README.md
  TODOs.md
  src/app.py
Labels: feature-request👓, size/S

#273 🧹 Cleanup
  main.py
  src/downloader/apkmirror.py
  src/downloader/apkpure.py
  src/downloader/apksos.py
  src/downloader/uptodown.py
  src/exceptions.py
  src/patches.py
  src/utils.py
Labels: chore🧹, size/M

#274 Improvements
  TODOs.md
  scripts/status_check.py
  src/downloader/download.py
  src/downloader/github.py
  src/parser.py
  src/patches.py
  src/utils.py
Labels: chore🧹, size/L

#278 Fix Messenger app name and URL
  README.md
Labels: size/XS

#277 Change Google Recorder source to Uptodown
  README.md
  src/config.py
  src/downloader/uptodown.py
Labels: size/M

#281 Extracted common methods
  scripts/status_check.py
  src/patches.py
  src/utils.py
Labels: chore🧹, size/M

#283 🎨 Use common function
  src/downloader/apksos.py
Labels: chore🧹, size/XS

#285 🎨 Extracted common parser string
  scripts/status_check.py
  src/downloader/uptodown.py
  src/utils.py
Labels: chore🧹, size/XS

#284 🎨 Use BS4 for scrapping
  requirements.txt
  src/downloader/apkmirror.py
  src/downloader/apksos.py
  src/downloader/uptodown.py
Labels: feature-request👓, size/L

#289 🎨 Chore
  .github/workflows/print-secrets.yml
  scripts/status_check.py
  src/config.py
  src/exceptions.py
  src/patches.py
  src/utils.py
Labels: chore🧹, size/L

#290 Exception handling
  main.py
  scripts/status_check.py
  src/downloader/apkmirror.py
  src/downloader/apkpure.py
  src/downloader/apksos.py
  src/downloader/download.py
  src/downloader/github.py
  src/downloader/uptodown.py
  src/exceptions.py
  src/patches.py
  src/utils.py
Labels: size/L

#296 🐛 Wrong version selection in APKMirror
  .github/workflows/pr-checks.yml
  src/downloader/apkmirror.py
Labels: size/M

#294 🎨 Moved apk sources out of config.
  .github/workflows/build-artifact.yml
  src/config.py
  src/downloader/apkmirror.py
  src/downloader/apkpure.py
  src/downloader/apksos.py
  src/downloader/factory.py
  src/downloader/sources.py
  src/downloader/uptodown.py
Labels: chore🧹, size/L

#297 🎨 Merge Bundle to get APK file
  .github/workflows/pr-checks.yml
  .gitignore
  main.py
  scripts/status_check.py
  src/app.py
  src/config.py
  src/downloader/apkmirror.py
  src/downloader/apkpure.py
  src/downloader/apksos.py
  src/downloader/download.py
  src/downloader/github.py
  src/downloader/sources.py
  src/downloader/uptodown.py
  src/parser.py
  src/utils.py
Labels: size/L

#301 🎨 Output app dl
  main.py
  src/app.py
  src/downloader/apkmirror.py
  src/downloader/apkpure.py
  src/downloader/apksos.py
  src/downloader/download.py
  src/downloader/github.py
  src/downloader/uptodown.py
Labels: chore🧹, size/M

#304 ✨ Use Dict for storing patches
  src/app.py
  src/downloader/apkmirror.py
  src/downloader/apkpure.py
  src/downloader/apksos.py
  src/downloader/download.py
  src/downloader/factory.py
  src/downloader/github.py
  src/downloader/sources.py
  src/downloader/uptodown.py
  src/patches.py
Labels: chore🧹, size/L

#305 🎨 Package name as attribute
  src/app.py
  src/downloader/apkpure.py
  src/downloader/apksos.py
Labels: chore🧹, size/S

#306 Feature/292 build any supported application
  .env.example
  README.md
  main.py
  src/app.py
  src/patches.py
Labels: feature-request👓, size/L

#307 Clean docs
  README.md
Labels: size/S

#308 🚨 Lint Fix
  .DS_Store
  .pre-commit-config.yaml
  Dockerfile
  README.md
  main.py
  pyproject.toml
  scripts/__init__.py
  scripts/status_check.py
  setup.cfg
  src/__init__.py
  src/app.py
  src/config.py
  src/downloader/__init__.py
  src/downloader/apkmirror.py
  src/downloader/apkpure.py
  src/downloader/apksos.py
  src/downloader/download.py
  src/downloader/factory.py
  src/downloader/github.py
  src/downloader/sources.py
  src/downloader/uptodown.py
  src/downloader/utils.py
  src/exceptions.py
  src/parser.py
  src/patches.py
  src/utils.py
Labels: chore🧹, size/XL

#309 🎨 Added Dockerfile
  .github/workflows/build-artifact.yml
  Dockerfile
  Dockerfile-base
  docker-compose.yml
Labels: feature-request👓, size/M

#310 Chore/base image
  .github/workflows/dockerhub-base.yml
  .github/workflows/newapp-check.yml
  .github/workflows/pre-commit.yml
  Dockerfile-base
Labels: chore🧹, size/S

#311 👷 Updated print-secrets.yml
  .github/workflows/print-secrets.yml
Labels: chore🧹, size/M

#312 Chore/issue template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: chore🧹, size/M

#313 📝 Added feature reques template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: chore🧹, size/M

#317 🎨 Added lightroom
  README.md
  src/downloader/sources.py
  src/patches.py
Labels: apkmirror⬇️, new-app💁‍, size/XS

#316 🎨 Added solidexplorer
  README.md
  src/downloader/sources.py
  src/patches.py
Labels: apkmirror⬇️, new-app💁‍, size/XS

#315 🎨 Added strava
  README.md
  src/downloader/sources.py
  src/patches.py
Labels: apkmirror⬇️, new-app💁‍, size/XS

#314 🎨 Added duolingo
  README.md
  src/downloader/sources.py
  src/patches.py
Labels: apkmirror⬇️, new-app💁‍, size/XS

#318 👷 Use Local compose
  .github/workflows/build-artifact.yml
Labels: chore🧹, size/XS

#319 👷 Use Local compose
  .github/workflows/build-artifact.yml
  .github/workflows/pr-checks.yml
Labels: chore🧹, size/XS

#320 🐛 Status Scrapper not scrapping icon from apkcombo
  scripts/status_check.py
  src/downloader/sources.py
  src/utils.py
Labels: bug🐞, size/M

#321 🐛 Added musically
  README.md
  src/downloader/sources.py
  src/patches.py
Labels: apkmirror⬇️, new-app💁‍, size/XS

#324 ✨ Added apkmonk scrapper
  README.md
  src/downloader/apkmonk.py
  src/downloader/factory.py
  src/downloader/sources.py
  src/exceptions.py
Labels: feature-request👓, size/L

#326 🎨 Added photomath
  README.md
  src/downloader/sources.py
  src/patches.py
Labels: new-app💁‍, size/XS, apkmonk⬇️

#327 🎨 Added apkmonk icon scrapper
  scripts/status_check.py
  src/downloader/sources.py
  src/exceptions.py
Labels: chore🧹, size/M

#329 🎨 Added joey
  README.md
  src/downloader/sources.py
  src/patches.py
Labels: new-app💁‍, size/XS, apkmonk⬇️

#330 🎨 Added vanced
  README.md
  src/downloader/sources.py
  src/patches.py
Labels: apkmirror⬇️, new-app💁‍, size/XS

#331 🎨 Added spotify-lite
  README.md
  src/downloader/sources.py
  src/patches.py
Labels: new-app💁‍, size/XS, apkmonk⬇️

#332 🎨 Added digitales
  README.md
  src/downloader/sources.py
  src/patches.py
Labels: new-app💁‍, size/XS, apkmonk⬇️

#333 🎨 Added scbeasy
  README.md
  src/downloader/sources.py
  src/patches.py
Labels: new-app💁‍, size/XS, apkmonk⬇️

#334 🎨 Added reddit-news
  README.md
  src/downloader/sources.py
  src/patches.py
Labels: new-app💁‍, size/XS, apkmonk⬇️

#335 🎨 Added finanz-online
  README.md
  src/downloader/sources.py
  src/patches.py
Labels: apksos⬇️, new-app💁‍, size/XS

#336 ✨ Added apkpure scrapper
  scripts/status_check.py
  src/downloader/sources.py
  src/exceptions.py
Labels: chore🧹, size/M

#339 🐛 Handle new v3 cli args
  .gitignore
  src/parser.py
Labels: bug🐞, size/S

#345 🎨 Updated error message
  main.py
  scripts/status_check.py
  src/app.py
  src/exceptions.py
Labels: chore🧹, size/M

#347 👷 Updated CI
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/dockerhub-base.yml
Labels: chore🧹, size/XS

#348 👷 Updated error handling
  .gitignore
  src/app.py
  src/exceptions.py
Labels: chore🧹, size/S

#350 👷 Updated apkmonk header
  src/downloader/apkmonk.py
Labels: chore🧹, size/S

#353 👽️ Updated Revanced API
  scripts/status_check.py
  src/downloader/sources.py
  src/exceptions.py
  src/utils.py
Labels: chore🧹, size/S

#355 Chore/status check
  .github/workflows/newapp-check.yml
Labels: chore🧹, size/XS

#357 🎨 Improved imports
  main.py
  src/app.py
  src/config.py
Labels: chore🧹, size/M

#361 👷 Added git in base image
  Dockerfile-base
Labels: size/XS

#359 ✨ Added google drive downloader
  README.md
  pyproject.toml
  requirements.txt
  src/config.py
  src/downloader/factory.py
  src/downloader/google_drive.py
  src/downloader/sources.py
Labels: feature-request👓, size/M
