Repository nikhilbadyal/docker-py-revanced, pull requests merged in 2023-12, with the labels that each got.

#415 🐛 Fix Uptodown downloader
  src/downloader/uptodown.py
Labels: size/M

#422 ✨ Apprise Integration
  .github/workflows/build-apk.yml
  README.md
Labels: feature-request👓, size/M

#424 ✨ Expect Apprise notify in workflow run
  .github/workflows/build-apk.yml
Labels: bug🐞, size/XS

#429 🐞 Updated inclusion logic
  src/parser.py
  src/patches.py
Labels: bug🐞, size/S
