Repository nikhilbadyal/docker-py-revanced, pull requests merged in 2023-10, with the labels that each got.

#388 🔥 CLI v4 Support
  README.md
  src/config.py
  src/parser.py
Labels: bug🐞, size/S

#390 💩 Handle v3 and v4 for now
  src/parser.py
Labels: bug🐞, size/S

#392 🔥 CLI v4
  README.md
  main.py
  src/app.py
  src/config.py
  src/parser.py
Labels: feature-request👓, size/L

#397 ✨ Updated ruff version
  .pre-commit-config.yaml
Labels: pre-commit✨, size/XS

#404 Update README.md for microg path
  README.md
Labels: size/XS
