Repository nikhilbadyal/docker-py-revanced, pull requests merged in 2024-04, with the labels that each got.

#480 Extract source instead to reuse in extracting divs
  src/downloader/apkmirror.py
Labels: size/S

#483 💥 Replace docker-compose with docker compose
  .github/workflows/build-artifact.yml
  README.md
Labels: bug🐞, size/XS

#488 ✨ Scraper improvements
  README.md
  src/downloader/apkmonk.py
  src/downloader/apkpure.py
  src/downloader/apksos.py
  src/downloader/factory.py
  src/downloader/sources.py
Labels: size/L

#489 🎨 Save patch resource version
  src/app.py
  src/downloader/github.py
  src/parser.py
  src/patches.py
Labels: chore🧹, size/M

#490 🎨 Save patch resource version
  .github/workflows/build-artifact.yml
  main.py
  src/utils.py
  updates.json
Labels: chore🧹, size/S

#491 🎨 Updated changelog file format
  main.py
  src/utils.py
Labels: chore🧹, size/M

#494 🐛 Fix changelog file format
  .github/workflows/build-artifact.yml
  src/utils.py
Labels: chore🧹, size/S

#496 ✨ Save patch time
  src/app.py
  src/utils.py
Labels: chore🧹, size/S

#498 🗑️ Refactored app constructor
  main.py
  src/app.py
Labels: chore🧹, size/XS

#499 ⬆️ Updated python version
  .github/workflows/newapp-check.yml
  Dockerfile-base
Labels: chore🧹, size/XS

#501 ♻️ Refactored strings
  src/config.py
  src/downloader/download.py
  src/downloader/utils.py
  src/utils.py
Labels: chore🧹, size/M

#504 ✨ Ability to override patch apps from GH UI
  .github/workflows/build-apk.yml
  .github/workflows/build-artifact.yml
  README.md
  requirements.txt
  scripts/prefered_apps.py
Labels: feature-request👓, size/M, enhancement, Review effort [1-5]: 2

#505 Filter to be patched
  .github/workflows/auto-release.yml
  .github/workflows/build-apk.yml
  check_resource_updates.py
Labels: feature-request👓, size/S, enhancement, Review effort [1-5]: 2

#506 ✨ Use updates json from other branch
  .github/workflows/build-artifact.yml
  main.py
  src/manager/github.py
  src/utils.py
Labels: feature-request👓, size/M, enhancement, Review effort [1-5]: 3

#512 ✨ Run builder when source is changed.
  check_resource_updates.py
  src/manager/github.py
  src/manager/release_manager.py
  src/utils.py
Labels: feature-request👓, size/M, enhancement, Review effort [1-5]: 3

#518 Revert "Docker Build Failing"
  .github/workflows/dockerhub-base.yml
  .github/workflows/dockerhub.yml
  Dockerfile
  README.md
  docker-compose.yml
Labels: size/S
